import Head from "next/head";
import Link from "next/link";
import { useAuthentication } from "../hooks/authentication";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { user } = useAuthentication();

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <p>{user?.uid || "未ログイン"}</p>
        <Link href="/page2">
          <a>Go to page2</a>
        </Link>
      </main>
    </>
  );
}
